### ISSUE TITLE
Refactor `DroneApiInterface` to Use Interface and Implementation Classes

### ISSUE THREAD

**Issue by zakaBouj** [Code-Hauptwache/DroneDeck#12]
#### Description
Refactor the `DroneApiInterface` class to follow the best practice of separating the interface and its implementation. This change will improve the modularity and maintainability of the code.

#### Tasks
1. **Create Interface:**
   - **File Name:** `IDroneApi.java`
   - **Directory Path:** `src/main/java/api`
   - **Description:** Define the method signatures for the `DroneApiInterface`.

2. **Create Implementation Class:**
   - **File Name:** `DroneApi.java`
   - **Directory Path:** `src/main/java/api`
   - **Description:** Implement the methods defined in the `IDroneApi` interface.

#### Notes
- Ensure that the new interface and implementation class are correctly referenced in the project.
- Update any existing references to `DroneApiInterface` to use the new `DroneApi` class where necessary.

**Comment by dominikKowalczyk17** [comment]
Hello ! Could I work on this issue ?
