### ISSUE TITLE
Implement Encrypted Storage for API Key

### ISSUE THREAD

**Issue by zakaBouj** [Code-Hauptwache/DroneDeck#14]
Below is the **updated issue description** with an added reference to **Issue #36**, which covers the UI implementation.

---

### **Description:**  
To improve flexibility, security, and usability, we will implement a system where the API key can be provided by the user at runtime and optionally saved in an encrypted format. To ensure robust encryption, the user will be required to provide a password if they choose to save the API key. On subsequent startups, the application will check for a saved key and prompt the user accordingly. This will make it easier to handle API key changes or reuse the project without recompiling, especially for future users.

For development purposes, the system should allow developers to disable the runtime prompt mechanism easily. Instead, the application should be capable of automatically fetching the API key from environment variables. This will streamline development workflows and align with the project's usage of IntelliJ IDEA as the primary IDE.

> **Note:** The UI portion of this feature, including the screens and user interactions for entering and saving API keys, is tracked separately in **Issue #39** .
>- #39 

---

### **Acceptance Criteria:**  
- [ ] On application startup, the user is prompted to provide their API key.  
- [ ] The user is asked if they want to save the API key securely.  
- [ ] If the user chooses to save the API key:  
  - The API key is encrypted using a password provided by the user.  
  - The encrypted API key is stored in a file within the application directory.  
- [ ] On subsequent startups:  
  - If a saved API key exists, the user is prompted to enter the password to decrypt it.  
  - If no saved API key exists, the user is prompted to enter a new API key.  
- [ ] If the saved API key or password is incorrect, clear and helpful error messages are displayed.  
- [ ] The system ensures that the encryption method is secure and not easily reversible without the correct password.  
- [ ] All usages of the API key in the project are updated to use this new mechanism.  
- [ ] The project documentation is updated to describe:  
  - How to provide the API key at runtime.  
  - How to save the API key securely.  
  - How to use a new or expired API key.  
  - How to disable the runtime prompt and use environment variables for development.

### **Development Mode Specifics:**  
- [ ] Introduce a configuration flag or environment variable to disable the runtime API key prompt.  
- [ ] Ensure that when the runtime prompt is disabled, the application automatically reads the API key from an environment variable (e.g., `API_KEY`).  
- [ ] Document the process of enabling and using this development mode, tailored for IntelliJ IDEA users.

**Comment by Gord310** [comment]
Just some thoughts, nothing of substance.

I think it would be good to ask the user on startup to input their API key and prompt them to decide if their key should be saved. For better encryption (), we should also ask the user for a password (if they choose to save their API key).

On application startup, we would then check if the user has a saved key. Depending on the situation, we would either ask them for their API key or their password.

- Prompt the user at startup to input their API key.
- Ask the user if they want to save their API key.
- If they choose to save the key, require a password for encryption.
- On subsequent startups, check if an API key is saved:
  - If not, prompt the user for their API key.
  - If saved, prompt the user for their password.

**Comment by zakaBouj** [comment]
> Just some thoughts, nothing of substance.
> 
> I think it would be good to ask the user on startup to input their API key and prompt them to decide if their key should be saved. For better encryption, we should also ask the user for a password (if they choose to save their API key).
> 
> On application startup, we would then check if the user has a saved key. Depending on the situation, we would either ask them for their API key or their password.
> 
> * Prompt the user at startup to input their API key.
> * Ask the user if they want to save their API key.
> * If they choose to save the key, require a password for encryption.
> * On subsequent startups, check if an API key is saved:
>   
>   * If not, prompt the user for their API key.
>   * If saved, prompt the user for their password.


Hey @Gord310, 

considering this is a class project and the API is accessible only through the university network or VPN, I think asking the user for an API token might not be necessary. Since the app is likely to be used mainly by our Java class, embedding the token securely (e.g., encrypted in the app) should suffice. This would also make the app easier to use for others within the university network

**Comment by Gord310** [comment]
> embedding the token securely (e.g., encrypted in the app) should suffice

Hey, @zakaBouj,

As far as I’m concerned, encryption only works with a "random" password for both encryption and decryption. Anything else is just obfuscation.

**Comment by zakaBouj** [comment]
> Hey, @zakaBouj,
> 
> As far as I’m concerned, encryption only works with a "random" password for both encryption and decryption. Anything else is just obfuscation.
> 
> Also, if I’m remembering correctly, we need to read from and write to a file within our application. I think the best (and most useful) option for this is using the ApiKey.
> 
> If the ApiKey ever expires, changes, or another group wants to test or use our project after we’ve graduated, they can simply use a new one without needing to recompile.

Hey @Gord310,

you have a great point i was missing on, i accordingly changed the issue description feel free to take a look and let me know if this is what you menat by.
